name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  plain_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Run tests (x86_64)
      run: cargo test

  miri_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Default to Nightly
      run: rustup default nightly
    
    - name: Add miri component
      run: rustup component add miri
    
    - name: Run miri tests (x86_64)
      run: cargo miri test

  cross_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: install cross-rs
      run: cargo install cross --git https://github.com/cross-rs/cross
    
    - name: Run cross tests (arm)
      run: cross test --target arm-unknown-linux-gnueabi
    
    - name: Run cross tests (arm + inline asm)
      run: cross test --target arm-unknown-linux-gnueabi --features armv4t
